### ISSUE TITLE
Searching the craftguide based on category

### ISSUE THREAD

**Issue by orbea** [minetest-mods/craftguide#103]
I added moreblocks to my game and now its very hard finding the desired block and recipe in the craftguide because of the shear abundance of block materials.

Maybe this could be improved if it was possible to find a list of item categories (e.g. `default`, `farming` or `moreblocks`) and optionally filter for those recipes or disable them so they do not appear in the search results. Basically some kind of advanced search feature.

Is this something that is possible or could be done?

**Comment by kilbith** [comment]
There is an API to create your own search filter: https://github.com/minetest-mods/craftguide/blob/master/API.md#search-filters

**Comment by orbea** [comment]
Thanks for pointing that out.
