### ISSUE TITLE
No crafts for some blocks on the first page

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/craftguide#11]
Installed 128413c version of crafting guide along default minetest_game. Running it in creative mode.
On the first page of crafting guide those crafts are not working, no recipe at all:
* Simple Bed
* Boat
* Lava bucket
* Brake rail
* Cart
* Rail
* Crafting guide
* Aspen Tree
* Leaves
* Apple
* Aspen Leaves
* Aspen Sapling

It seems next pages are not affected. Bug appeared in revision https://github.com/minetest-mods/craftguide/commit/f3ce043a5394a19f551a69cf7a0956cd8155407c

**Comment by tchncs** [comment]
Today i updated xdecor and added the craftguide mod speratly - all pages are dead in my singleplayer game on the latest commit.

**Comment by kilbith** [comment]
@tchncs What do you mean by "all pages are dead" exactly ?

**Comment by tchncs** [comment]
@kilbith just nothing happens on click of any item on all pages.

**Comment by kilbith** [comment]
@tchncs Is there a place where I could download the subgame you're using ? Also did you try with Minetest Game only ?

**Comment by tchncs** [comment]
The subgame is located [here](https://git.tchncs.de/Illuna-Minetest/minetest_game/tree/master/mods). I am not quite sure but all submodules should be public.

I didn't tried a clean subgame yet.

**Comment by kilbith** [comment]
@tchncs I'm not able to clone your repository, it asks for an username/password : 

```
Cloning in '/home/jp/dev/minetest/games/illuna/minetest_game/mods/ranks'...
Username for 'https://git.tchncs.de': 
Password for 'https://n@git.tchncs.de': 
remote: HTTP Basic: Access denied
```

**Comment by tchncs** [comment]
I am sorry, it should be public but gitlab ignores this setting somehow.
You can get our ranks fork from [here](http://illuna-minetest.tk/ranks.tar) as an archive.

**Comment by kilbith** [comment]
@tchncs The problem is that it aborts the cloning if I don't provide the username/password. Feel free to give me a compressed archive with all submodules included.

**Comment by tchncs** [comment]
But you could just delete the submodule entry from `.gitmodules` :3

**Comment by kilbith** [comment]
Well, I'm still unable to get your subgame even when messing the `.gitmodules`.

**Comment by tchncs** [comment]
https://illuna-minetest.tk/minetest_game.tar

**Comment by kilbith** [comment]
Thanks for the archive, @tchncs (I'll delete all the off-topic comments in the issue now).

So I checked with your subgame and I confirm that `craftguide` works perfectly fine with it.

#### Summarize of the situation : #### 
- The issue is only reproducible among a few users ;
- The issue has no common pattern (i.e. @Fixer-007 is having the issue only in Page 1 with some items; while @tchncs is having the issue with *all* items on *all* pages) ;
- The issue seems influenced with the `language =` setting in `minetest.conf` (@Fixer-007, correct me if I'm wrong).
- The issue has _random_ symptoms among the userbase, therefore it is hard to have a starting clue of where it could goes wrong into the mod's code (which looks correct).

This suggests me an engine bug for the moment.

**Comment by Fixer-007** [comment]
* it may have some connection to minetest settings
* i've tried it with dreambuilder and I got nonworking crafts on many pages too

**Comment by kilbith** [comment]
I tried with `dreambuilder` as well and everything was functional.

**Comment by kilbith** [comment]
I confirm the issue is only happening on Minetest 0.4.14-**stable**. Try out on a engine development version or the upcoming 0.4.15-stable.

**Comment by Fixer-007** [comment]
Happens to me on newest builds

**Comment by tchncs** [comment]
> Happens to me on newest builds

+1

**Comment by taikedz** [comment]
Last commit trying to fix this one breaks.

Line 338 is presuming it gets the item on first go, but the table offers no such guarantee

**Comment by taikedz** [comment]
Problem #11 was likely this one line
https://github.com/minetest-mods/craftguide/commit/d0b3cf2887238275894b067f929f6c00a5d221a1#diff-d7d74284e2e39f6c06d199c8e2bedbd0L340

**Comment by kilbith** [comment]
@taikedz No, it was happening even when the loop was there. Also when pressing the button, its field is always in first position. The issue is very likely in the engine.

**Comment by kilbith** [comment]
Normally fixed : https://github.com/minetest-mods/craftguide/commit/fa7a50fe

**Comment by tchncs** [comment]
I can confirm, works wonderful now. :)

**Comment by Fixer-007** [comment]
same for me
