### ISSUE TITLE
Attempt to index local 'meta' (a nil value)

### ISSUE THREAD

**Issue by limitedAtonement** [minetest-mods/craftguide#110]
terminate called after throwing an instance of 'LuaError'
      what():  Runtime error from mod 'craftguide' in callback on_shutdown(): /root/.minetest/mods/craftguide/init.lua:2010: attempt to index local 'meta' (a nil value)
    stack traceback:
            /root/.minetest/mods/craftguide/init.lua:2010: in function 'save_meta'
            /root/.minetest/mods/craftguide/init.lua:2022: in function '?'
            /usr/share/minetest/builtin/game/register.lua:429: in function </usr/share/minetest/builtin/game/register.lua:413>

I'm not sure what causes this to happen; it seems to happen randomly.

**Comment by kilbith** [comment]
You must update the mod.

**Comment by limitedAtonement** [comment]
I had this problem a week or so ago and realized I should update. At that time I updated to tag 1.13 (103624b) which appears to be the most recent release. To which commit should I update?

**Comment by kilbith** [comment]
Latest.

**Comment by limitedAtonement** [comment]
Okay, I'll use 7ef62f4 and come back if I have more problems. Thank you!
