### ISSUE TITLE
Mod crashes

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/craftguide#111]
When I use the crafting book or sign, the mod crashes:

```
When I use the crafting book or sign, the mod crashes:

```
AsyncErr: ServerThread::run Lua: Runtime error from mod 'craftguide' in callback item_OnUse(): ~/.minetest/mods/craftguide/init.lua:1120: attempt to get length of field 'items' (a nil value)
stack traceback:
	~/.minetest/mods/craftguide/init.lua:1120: in function 'make_fs'
	~/.minetest/mods/craftguide/init.lua:1712: in function 'on_use'
	~/.minetest/mods/craftguide/init.lua:1722: in function <~/.minetest/mods/craftguide/init.lua:1721>
```

556037480146c7c0bfc54d79bdd4b11aca59d1d0
```

556037480146c7c0bfc54d79bdd4b11aca59d1d0

**Comment by kilbith** [comment]
Can you reproduce on the lastest commit ?

**Comment by kilbith** [comment]
Actually this has been fixed long time ago already: https://github.com/minetest-mods/craftguide/issues/108
