### ISSUE TITLE
Some blocks are missing from guide

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/craftguide#12]
... like gravel and ice. Revision d0b3cf2
As example, creative inventory:
![inv](https://cloud.githubusercontent.com/assets/16494741/21296098/151adbd0-c56c-11e6-86a3-c5b02844bac1.png)
Crafting guide:
![guide](https://cloud.githubusercontent.com/assets/16494741/21296102/1f111762-c56c-11e6-82fd-72f3cd8b31ac.png)
Some blocks are missing, you can't find them via search either.

**Comment by kilbith** [comment]
Only items that are craftable OR fuels are listed. Gravel and ice are not craftable and are not fuels.
