### ISSUE TITLE
Some wool recipes display the wrong dye

### ISSUE THREAD

**Issue by whitephoenix0** [minetest-mods/craftguide#22]
Green wool, magenta wool, and red wool display the correct tooltip but the wrong dye in their recipes. Green wool shows wool + dark green dye, magenta wool shows wool + purple dye, and red wool show wool + pink dye.

**Comment by kilbith** [comment]
@Wuzzy2 Could you investigate please? I'm too lazy to work on my mods anymore.

**Comment by Wuzzy2** [comment]
Nope.

**Comment by kilbith** [comment]
Cannot reproduce, maybe an issue in your own subgame.
