### ISSUE TITLE
PNG warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by SnarkBoojum** [minetest-mods/craftguide#23]
It looks like some of the png files in the textures directory trigger warnings with recent versions of libpng. To fix them, using "mogrify *.png" is enough to fix things.

**Comment by kilbith** [comment]
Upstream issue.

**Comment by SnarkBoojum** [comment]
What do you mean by "upstream issue"? Mogrifying the png files in textures/ fixes the warnings, so I really think the problem is in the craftguide sources.

**Comment by SnarkBoojum** [comment]
You didn't take into account the fact that mogrifying the files in craftguide fixes things : that proves the png files are the problem.

Searching around on the net, it looks like more recent versions of libpng will print warnings where the previous ones didn't : you'll get more reports as those versions get in distributions. And at some point, you'll see them too...

Could you please reopen the issue?

**Comment by jastevenson303** [comment]
The images are likely part of minetest_game, or some other mods, and the issue lies there with them.  This mod only comes with one or two images, and surely you're not suggesting they're in error?

If so, perhaps you can provide the corrected files?

**Comment by SnarkBoojum** [comment]
I'm not suggesting they are : I affirm they are, otherwise mogrifying them wouldn't fix the issue.

Here are the files after mogrification:
![craftguide_arrow](https://user-images.githubusercontent.com/4647429/31247159-0ca32b5e-aa10-11e7-800f-94746d7066ba.png)
![craftguide_bg](https://user-images.githubusercontent.com/4647429/31247160-0ca46c08-aa10-11e7-84fc-715087ad2059.png)
![craftguide_book](https://user-images.githubusercontent.com/4647429/31247161-0ca7fc38-aa10-11e7-9868-228ee498ec04.png)
![craftguide_fire](https://user-images.githubusercontent.com/4647429/31247162-0caa9e20-aa10-11e7-8b7c-a2be90443cec.png)
![craftguide_furnace](https://user-images.githubusercontent.com/4647429/31247163-0cb0185a-aa10-11e7-8342-141b31d8f718.png)
![craftguide_shapeless](https://user-images.githubusercontent.com/4647429/31247164-0cb96bf8-aa10-11e7-89aa-498fbad1f2d7.png)
![craftguide_sign](https://user-images.githubusercontent.com/4647429/31247165-0cc61074-aa10-11e7-99aa-1734ee210644.png)
![craftguide_sign_inv](https://user-images.githubusercontent.com/4647429/31247166-0cc6742e-aa10-11e7-8721-623cdea8c47e.png)

**Comment by SnarkBoojum** [comment]
It's annoying, because the issue is closed while the problem is still open!
