### ISSUE TITLE
Update to new config api

### ISSUE THREAD

**Issue by SnarkBoojum** [minetest-mods/craftguide#24]
The following patch updates the code to the new config api:
[update_config_api.txt](https://github.com/minetest-mods/craftguide/files/1353859/update_config_api.txt)

**Comment by kilbith** [comment]
Not a proper patch and something very minor that I already have in mind, but I will not update yet.

**Comment by SnarkBoojum** [comment]
What do you mean by not a proper patch? There are other modules for which I wrote similar patches, so if there's a problem with that one, I might have to update them too :-(
