### ISSUE TITLE
Make the mod support translations?

### ISSUE THREAD

**Issue by MuhdNurHidayat** [minetest-mods/craftguide#26]
This mod contains English words like "Alternate", "Burning time" etc.

Will it be possible to make the mod support translation? You could implement any kind of translation tools, not just intllib (though it's more convenient to use intllib as it has gettext .po support)

**Comment by kilbith** [comment]
https://github.com/minetest-mods/craftguide/commit/95518c3725c5d792afda9c077f87328cb96c8aa1
