### ISSUE TITLE
Relicense under more permissive license?

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/craftguide#27]
Hello. Can you do me a favor?

Can you please relicense this under the MIT License or a similar permissive license? Or if you don't want that: LGPLv2.1 (preferably with the “or later” clause).

There are some subgames (including my own) licenced under the LGPL (mainly because it's the license which Minetest uses) and it would be hard, if not impossible to *legally* include your mod into subgames, as the GPLv3 is incompatible with any version of the LGPL.

Personally, I think the MIT License makes more sense because it lowers the entry barrier for subgame inclusion the most. But as I said, LPGL would be fine, too.

**Comment by kilbith** [comment]
I'm fine with the MIT license. If this mod can plug everywhere (technically), its license should follow the same "philosophy".

**Comment by Wuzzy2** [comment]
Thanks, good to hear.

So, change the `LICENSE` file then, please? (to make it official)

**Comment by kilbith** [comment]
https://github.com/minetest-mods/craftguide/commit/64a711530f4503644b08ce98f920dbe5eccba743
