### ISSUE TITLE
Suggestion: Usage

### ISSUE THREAD

**Issue by ChristianSirolli** [minetest-mods/craftguide#30]
Occasionally I play on servers that use Unified Inventory. The built-in crafting guide also allows users to see what materials are used for. If it is not outside of the scope of this mod, could it be possible for this to be a new feature in this mod? I love craftguide, but I miss being able to view item's usage.

**Comment by kilbith** [comment]
Not sure what you mean. Some examples please?

**Comment by ChristianSirolli** [comment]
In [Unified Inventory](https://github.com/minetest-mods/unified_inventory/blob/master/api.lua), it contains a craft guide. When clicking on an item, it first shows you the recipes like craftguide does. When clicking on the item again, it shows you what recipes the item is used in.

**Comment by kilbith** [comment]
I’m lazy. Show me some screenshots.

**Comment by ChristianSirolli** [comment]
LOL. The first picture is of the craft guide showing how to craft a bronze ingot. The second picture is of the craft guide showing what the bronze ingot is used for. Your craft guide can do the first part, but it can't show the usage like this one can.
![screenshot_20180522_153415](https://user-images.githubusercontent.com/18651961/40385849-ed551ea4-5dd5-11e8-8f6c-8d62256c9a22.png)
![screenshot_20180522_153444](https://user-images.githubusercontent.com/18651961/40385850-ed7cbb3a-5dd5-11e8-98bc-d78dffa96ff4.png)

**Comment by kilbith** [comment]
@Wuzzy2 Any thought?

**Comment by kilbith** [comment]
a3e18a1

**Comment by kilbith** [comment]
4bdd06a
