### ISSUE TITLE
Cannot craft blue book

### ISSUE THREAD

**Issue by MarvelWild** [minetest-mods/craftguide#35]
Latest commit atm
![mc-book](https://user-images.githubusercontent.com/7306230/43860993-2f5913b2-9b5e-11e8-813e-25cca8e12b77.png)

**Comment by pauloue** [comment]
It works for me. Is the mod loaded and it that a default:book?

**Comment by MarvelWild** [comment]
I just didn't enable the mods, expecting them to work minecraft way - just put into folder.
