### ISSUE TITLE
One specific technic recipe not recognized

### ISSUE THREAD

**Issue by 4w** [minetest-mods/craftguide#36]
The LV Furnace seems not to be recognized when searching for `furnace` (and other related keywords) although it has a recipe and crafting it works. Unified inventory for example has no issues finding the furnace and showing the recipe – so it generally is registered as expected.

![2018-09-03-060108_618x298_scrot](https://user-images.githubusercontent.com/30605057/44967011-cef81c80-af3e-11e8-9f44-97d13949a1fb.png)

![2018-09-03-060116_664x399_scrot](https://user-images.githubusercontent.com/30605057/44967014-d0294980-af3e-11e8-9fd5-31072c1389c2.png)

![2018-09-03-060400_1138x416_scrot](https://user-images.githubusercontent.com/30605057/44967108-3c0bb200-af3f-11e8-966e-d4ae10b0b927.png)

```
~/.minetest/mods/craftguide$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean


~/.minetest/mods/unified_inventory$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

```
~/.minetest/worlds/test $ grep ' = true' world.mt 
creative_mode = true
load_mod_mesecons_extrawires = true
load_mod_mesecons_lamp = true
load_mod_mesecons_hydroturbine = true
load_mod_mesecons_torch = true
load_mod_mesecons_wires = true
load_mod_mesecons_powerplant = true
load_mod_mesecons_gates = true
load_mod_mesecons_random = true
load_mod_mesecons_insulated = true
load_mod_mesecons_receiver = true
load_mod_mesecons = true
load_mod_mesecons_doors = true
load_mod_mesecons_switch = true
load_mod_mesecons_luacontroller = true
load_mod_mesecons_solarpanel = true
load_mod_mesecons_detector = true
load_mod_craftguide = true
load_mod_mesecons_commandblock = true
load_mod_mesecons_button = true
load_mod_extranodes = true
load_mod_technic_chests = true
load_mod_mesecons_blinkyplant = true
load_mod_wrench = true
load_mod_mesecons_lightstone = true
load_mod_mesecons_delayer = true
load_mod_mesecons_fpga = true
load_mod_mesecons_pressureplates = true
load_mod_mesecons_walllever = true
load_mod_mesecons_alias = true
load_mod_mesecons_stickyblocks = true
load_mod_mesecons_microcontroller = true
load_mod_mesecons_materials = true
load_mod_mesecons_movestones = true
load_mod_mesecons_mvps = true
load_mod_concrete = true
load_mod_mesecons_noteblock = true
load_mod_mesecons_pistons = true
load_mod_technic = true
load_mod_technic_worldgen = true
load_mod_pipeworks = true
load_mod_unified_inventory = true
```

**Comment by kilbith** [comment]
This furnace' craft is [registered](https://github.com/minetest-mods/technic/blob/master/technic/machines/LV/electric_furnace.lua#L6) for `technic:electric_furnace`, but then the node name is [aliased](https://github.com/minetest-mods/technic/blob/master/technic/legacy.lua#L16) to `technic:lv_electric_furnace`.

It is entirely possible to apply some specific glue to `craftguide` but it is cleaner to fix the node name in `technic` instead. And even better having access to a table of all registered aliases.

**Comment by 4w** [comment]
Thanks for the feedback. Opened an issue there.
