### ISSUE TITLE
attempt to call field 'register_on_mods_loaded' (a nil value)

### ISSUE THREAD

**Issue by Linuxdirk** [minetest-mods/craftguide#44]
Seems like this particular commit added the code

https://github.com/minetest-mods/craftguide/commit/b2a7f5430ace197e5eadb81e6b42ea133d4113a6#diff-d7d74284e2e39f6c06d199c8e2bedbd0R384

This causes a crash in current stable Minetest version 0.4.17.1 when on `master` branch of craftguide because `minetest.register_on_mods_loaded` is an upcoming 5.0.0 feature.

**Comment by kilbith** [comment]
Yes, this is why I warned the users about it on the forum topic: https://forum.minetest.net/viewtopic.php?p=338231#p338231

A download link is still provided for the 0.4.17-compatible version: [here](https://github.com/minetest-mods/craftguide/archive/0b4f202ffb2d1a4f3d1e2c5ffcad299a388b39ed.zip). Although I should create a separate branch with some backports.

**Comment by Linuxdirk** [comment]
Thanks, confirmed :)
