### ISSUE TITLE
Misleading message when using /craft on node that you don't know its recipe of yet [Progressive Mode]

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/craftguide#58]
If you are in progressive mode, started out with an empty craftguide, then you walk to a stone and type in `/craft`, the game claims there is no recipe for it.

When you mine the stone (thus reveal its recipes), then use the same command on another stone, it suddenly works.

I think this behaviour is actually correct in principle (you first have to collect the source item to “earn” more recipes), but the message is VERY misleading.

It says “No recipe for this node: X” but this isn't true. There is a recipe, you just don't know it yet. ;-)

I suggest:
In Progressive Mode, the error message should say “You don't know a recipe for this node: X”. This implies there might be a recipe for the stone, you just haven't found it out yet.

**Comment by kilbith** [comment]
I do agree.

**Comment by kilbith** [comment]
https://github.com/minetest-mods/craftguide/commit/e37f1df6d3442c882ffa5d0deac86cb810a6b823
