### ISSUE TITLE
API call to open crafting guide

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/craftguide#59]
I suggest to add an API call which I would consider very crucial and important would be “open the crafting guide”. xD

It could look like this:

`craftguide.show(selected_item, is_reverse)`
→ opens craft guide with the current filter applied.
→ `selected_item`: optional param, if set, this item is pre-selected. If the item does not exist or has no recipe, use the player's previous selection. By default, player's previous selection is used
→ `is_reverse`: optional param. if true, use reverse crafting mode, if false, use “forwards crafting” mode, if nil, use player's previous selection

**Comment by kilbith** [comment]
https://github.com/minetest-mods/craftguide/commit/aac3e3f693d082171122508ea7e561db1f46091e
