### ISSUE TITLE
Show group instead white item

### ISSUE THREAD

**Issue by amadin** [minetest-mods/craftguide#6]
With "Backed clay" mod craftguide show group instead "White backed clay". Is this normal?

![screenshot_20161104_161522](https://cloud.githubusercontent.com/assets/13412191/20008718/92b871b0-a299-11e6-9ae3-cddd0d295802.png)

**Comment by tenplus1** [comment]
Yes it is perfectly normal, showing that the recipe can use a group of items (e.g. ANY baked clay colour) in recipe.

**Comment by amadin** [comment]
But for wool showing group with white wool texture.

**Comment by sofar** [comment]
This mod relies on the mixing recipes. If you can make white wool through some mixing recipe, then this mod will show it. If you can't see it, then that means that there is no recipe that can make the item, group or not.

**Comment by amadin** [comment]
Then i asked i meant mods which have white colored block (for example in "Bakedclay clay" mod this is "bakedclay:white") but craftguide show group white texture only for wool. If you replace  item:sub(-4) == "wool"  by `item:sub(-9) == "bakedclay"` in the begin craftguide code then you will see this:

![screenshot_20161105_114426](https://cloud.githubusercontent.com/assets/13412191/20029154/e58f73b8-a33c-11e6-8351-5a609942976e.png)

I would not bother you if i found manual for get_recipe and item:sub
