### ISSUE TITLE
Error message in empty craftguide in Progressive Mode is misleading

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/craftguide#62]
In progressive mode, you currently start out with an empty crafting guide, but if you open the craftguide, the error message is not helpful: “no items to show”.

Please add a hint, something like like: “Collect items to reveal more recipes.”. This hint should only be shown if all of these conditions are true:
- Progressive Mode is active
- Search has been reset
- There exists at least one recipe in the game

**Comment by kilbith** [comment]
https://github.com/minetest-mods/craftguide/commit/1ba1e41dcd89576208570bea82e3d6b6c982e1ed
