### ISSUE TITLE
French translations cause bad display

### ISSUE THREAD

**Issue by kilbith** [minetest-mods/craftguide#72]
```
2019-02-22 15:06:54: ERROR[Main]: Malformed translation line "
2019-02-22 15:06:54: ERROR[Main]: "
```

The locale file: https://github.com/minetest-mods/craftguide/blob/master/locale/craftguide.fr.tr

Looks like a newline is appended to every string.

OS: Windows 10.

![53183804-4b211200-35fc-11e9-8396-ba000700a395](https://user-images.githubusercontent.com/7883281/53247464-be398f80-36b3-11e9-89c9-f711ea8c5ba7.png)

@Wuzzy2 says the german translations do not cause that.

@Ekdohibs Any explanation?

**Comment by Wuzzy2** [comment]
Which MT version? Maybe you found a bug in MT.

**Comment by kilbith** [comment]
5.0 RC1 from https://forum.minetest.net/viewtopic.php?f=18&t=22078

**Comment by Ekdohibs** [comment]
Could be related to https://github.com/minetest/minetest/issues/8189 - is your file using CRLF line endings?

**Comment by kilbith** [comment]
> is your file using CRLF line endings?

Yes.

**Comment by pauloue** [comment]
https://github.com/minetest/minetest/pull/8280 fixes it for me (with a manually inserted carriage return)

**Comment by kilbith** [comment]
https://github.com/minetest/minetest/commit/eeb67627ec75f9c42e089b5e90686017b7eb62c8
