### ISSUE TITLE
Crash in progressive mode when player leaves server

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/craftguide#79]
If a player leaves the server while progressive mode is active, the mod crashes!

Originally found by RonnyBarthmann:
https://git.minetest.land/Wuzzy/MineClone2/issues/516#issuecomment-8507

My fix on my fork of `craftguide`:
https://repo.or.cz/MineClone/MineClone2.git/commitdiff/78e5322f5791718d9afdef9c67d21f3be152d2cd?hp=50db5f5b855a59b53c27c36769adee66100527e5

**Comment by kilbith** [comment]
Thanks for reporting.

https://github.com/minetest-mods/craftguide/commit/4c0371c5cc01a5fd3103ab4109b7d4788e094ddb
