### ISSUE TITLE
Pressing Enter for searching seems unreliable

### ISSUE THREAD

**Issue by kilbith** [minetest-mods/craftguide#8]
I have no idea what's going on, but sometimes the formspec closes after pressing Enter for doing a search (the filtering is correctly applied, though).

**Comment by Fixer-007** [comment]
Can confirm this.

**Comment by dsohler** [comment]
Can confirm, too.

Sometimes it simply closes. When re-opening the searched stuff is shown. When pressing enter it closes again.

**Comment by sofar** [comment]
696530e

**Comment by sofar** [comment]
if you can, please check!

**Comment by dsohler** [comment]
Tried my best to close on enter but was not able to. Since this is an infrequent bug I suggest some more time for testing.

**Comment by Fixer-007** [comment]
It seems to be fixed for me.

**Comment by dsohler** [comment]
During the testing of other stuff during the last 2 days Craftguide didn't close for me when pressing enter.
