### ISSUE TITLE
Can't use area-tooltips on item buttons

### ISSUE THREAD

**Issue by kilbith** [minetest-mods/craftguide#80]
I'd like to use area-tooltips on certain item image buttons, as they show up quicker than the element-tooltips and for another technical reason. Problem: there is no way to override the default tooltips on the item buttons, they show up right after the area-tooltips.

**Cc:** @rubenwardy @SmallJoker

**Comment by SmallJoker** [comment]
This appears to be a priority issue. Since the drawing order is fixed, and also the tooltip handling, I'd like to know how you would want to define which tooltip has to be shown above any other.

**Comment by Linuxdirk** [comment]
Rendering order issue?

https://forum.minetest.net/viewtopic.php?t=21691#p339399  
https://github.com/minetest/minetest/issues/8036

**Comment by Wuzzy2** [comment]
Just because they appear quicker? No, tooltips on buttons should not appear instantly. Also, it's the user's choice how long the tooltip delay is.

**Comment by kilbith** [comment]
Solution: formspec version 3
