### ISSUE TITLE
register_craft is broken

### ISSUE THREAD

**Issue by LunaSquee** [minetest-mods/craftguide#82]
[This function](https://github.com/minetest-mods/craftguide/blob/master/init.lua#L142) checks that the variables provided must all be strings, but that's clearly not the case. `width` is a number and `items` is a table.

**Comment by kilbith** [comment]
Oh yes, this is an oversight, sorry.

**Comment by kilbith** [comment]
https://github.com/minetest-mods/craftguide/commit/9dc656d5a22f7cd7739fc3d36b804aa1577b5d5a
