### ISSUE TITLE
Lava Bucket “Replaced by Empty Bucket on crafting”

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/craftguide#87]
This text shows up in tooltip of lava bucket. [Minetest Game]

It's correct that it will be replaced, but by crafting? No.

This is a fuel recipe, so the item will be replaced not by crafting, but by burning / being used as fuel. Two possibilities:

* Either change the text to “Replaced by Empty Bucket”
* Or change text to appropriate text depending on craft type:
    * Crafting: “Replaced by Empty Bucket on crafting”
    * Smelting: “Replaced by Empty Bucket on smelting”
    * Fuel: “Replaced by Empty Bucket on burning”

**Comment by kilbith** [comment]
Oh yes, good catch. Thanks.

**Comment by kilbith** [comment]
https://github.com/minetest-mods/craftguide/commit/84795a65238345ccbe4a5d56c4ddf338c922051a
