### ISSUE TITLE
Some recipes not being shown

### ISSUE THREAD

**Issue by h4ml3t** [minetest-mods/craftguide#89]
In [Hamlet's Quest](https://git.minetest.land/Hamlet/hamlets_quest) mods are stored in subfolders, or modpacks.

In MT v0.4.17 everything was fine, now the craftguide isn't showing the recipes of some mods.

These are: [anvil](https://github.com/minetest-mods/anvil), [handholds](https://github.com/Ezhh/handholds), [breadcrumbs](https://github.com/minetest-mods/breadcrumbs), [sounding_line](https://github.com/minetest-mods/sounding_line) and [ropes](https://github.com/minetest-mods/ropes).

I have tried updating each and every mod's mod.conf, I have tried with the new modpack.conf, eventually I've discovered that moving player_api in the mods' root folder (../minetest/games/game/mods/) helped to show some more recipes (don't ask me why). I have also tried removing the [hq_tweaks](https://git.minetest.land/Hamlet/hamlets_quest/src/branch/master/mods/hq_tweaks) folder to be sure that no modifications done by me were interfering.

Eventually I tried moving every mod from the modpacks (../minetest/games/game/mods/modpack/) to the mods' root folder (../minetest/games/game/mods/), and the craftguide was correctly showing every recipe.

Until I tried the [gravelsieve](https://github.com/joe7575/Minetest-Gravelsieve) mod (which I had put in ../minetest/mods/), once again the recipe wasn't being shown.

Have you any idea why this could be possibly happening? I am getting crazy trying to figure where is the issue.

**Comment by kilbith** [comment]
Which commit are you on?

**Comment by h4ml3t** [comment]
I was on https://github.com/minetest-mods/craftguide/commit/732535c9da279b9bd115f0f6cb6892bcf3406cbd (the one after https://github.com/minetest-mods/craftguide/issues/88); however I've downloaded the latest one and it fixed my game's issue.

Sill, there's something strange with the Gravelsieve mod: I have tried loading it on MTG v5.0.1 with the latest craftguide's version, and it isn't showing the [sieve](https://github.com/joe7575/Minetest-Gravelsieve/blob/42677cbb2e6346b28cb90752796a2a5d7e20c137/init.lua#L451) and [auto_sieve](https://github.com/joe7575/Minetest-Gravelsieve/blob/42677cbb2e6346b28cb90752796a2a5d7e20c137/init.lua#L460) recipes, but it is showing the [compressed_gravel](https://github.com/joe7575/Minetest-Gravelsieve/blob/42677cbb2e6346b28cb90752796a2a5d7e20c137/init.lua#L467) and the [hammer](https://github.com/joe7575/Minetest-Gravelsieve/blob/42677cbb2e6346b28cb90752796a2a5d7e20c137/hammer.lua#L60) recipes. ???
This is happening on a clean MT & MTG v5.0.1 installation.

Can you reproduce the issue?

**Comment by kilbith** [comment]
That's because there are aliases registered next after the craft declarations. This isn't good practice, however that should be fixable.

**Comment by h4ml3t** [comment]
> That's because there are aliases registered next after the craft declarations. This isn't good practice, however that should be fixable.

Ah, probably something that the mod's developer wasn't aware of - just like me!
Let me know if you need help with testing, thank you in advance for looking into this.

**Comment by kilbith** [comment]
That should work now: https://github.com/minetest-mods/craftguide/commit/aef1fe0dc6863cff47312068a7519c9b03b8012f
